---
title: "Untitled"
author: "Andrés Molina Ribagorda"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


````{r warning = FALSE, message = FALSE}
library(clusterProfiler)
library(org.Mm.eg.db)
library(ggplot2)
library(ggkegg)
library(enrichplot)
library(DESeq2)
library(DOSE)
library(plotly)
library(visNetwork)
library(tidygraph)
library(dplyr)
library(ggraph)
library(ggplot2)
library(rmarkdown)
library(htmltools)
library(UpSetR)
library(ggupset)
library(ReactomePA)
library(writexl)
library(openxlsx)
library(pathview)
````

````{r}
#Functions section

# Function to rename column names to their first word
rename_columns_to_first_word <- function(data) {
  
  data <- data %>%
    rename_with(~ sapply(strsplit(.x, "_"), `[`, 1)) 
  return(data)
}

# Function to filter data and rename its columns
create_filtered_data <- function(data, param=NULL) {
  selected_columns <- data 
  
  selected_columns <- rename_columns_to_first_word(selected_columns)
  return(selected_columns)
}

# Function to filter data and rename its columns
get_data_by_param <- function(param) {
  
  if (!param %in% c("bayes", "deq", "empire", "rob")) {
    stop("El parámetro debe ser uno de: 'bayes', 'deq', 'empire', 'rob'")
  }
  
   # Constructs the variable name to search in the global environment
  variable_name <- paste0(param, "_data")
  
  
  if (!exists(variable_name, envir = .GlobalEnv)) {
    stop(paste("La variable", variable_name, "no existe en el entorno global"))
  }
  
  return(get(variable_name, envir = .GlobalEnv))
}

# Function to capitalize the first letter of a string
capitalize_first <- function(text) {
  paste0(toupper(substr(text, 1, 1)), tolower(substr(text, 2, nchar(text))))
}

# Function to generate filtered gene lists
generate_genes <- function(result, up, down,i){
  # Filters regulated genes based on a predefined list
  downregulated_genes_symbol <- sapply(result$datos_down$gene[sapply(result$datos_down$gene, capitalize_first) %in% sapply(down[,i],capitalize_first)], capitalize_first)
  upregulated_genes_symbol <- sapply(result$datos_up$gene[sapply(result$datos_up$gene, capitalize_first) %in% sapply(up[,i], capitalize_first)], capitalize_first)
  
  downregulated_genes_filtered <- result$data_down$ENTREZID[result$data_down$ENTREZID %in% down_entrez$ENTREZID]
  upregulated_genes_filtered <- result$data_up$ENTREZID[result$data_up$ENTREZID %in% up_entrez$ENTREZID]

  return(list(downregulated_genes_symbol = downregulated_genes_symbol, upregulated_genes_symbol = upregulated_genes_symbol, downregulated_genes_filtered = downregulated_genes_filtered, upregulated_genes_filtered = upregulated_genes_filtered))
}

# Function to generate data subsets based on logFC and p-value thresholds
generate_data <- function(datos, i, p.value){
  
  data_down <- datos[datos$logFC< -0.5 & datos$pvalue < p.value,]
  data_up <- datos[datos$logFC > 0.5 & datos$pvalue < p.value,]
  
  data_down <- data_down[order(data_down$pvalue), ]
  data_up <- data_up[order(data_up$pvalue), ]
 if (!is.null(dim(genes_up)) & !is.null(dim(genes_down))){
  datos_down <- data_down[data_down$gene %in% sapply(genes_down[,i],capitalize_first),]
  datos_up <- data_up[data_up$gene %in% sapply(genes_up[,i],capitalize_first),]
 }
  else{
    datos_down <- data_down
    datos_up <- data_up
  }
  
  return(list(data_down = data_down, data_up = data_up, datos_down = datos_down, datos_up = datos_up))
}

# Function to write data subsets to Excel files
write_dataframe <- function(dataframes, directory, param){
  write.xlsx(dataframes$down, file = paste0(directory,"/",param,"_down.xlsx"))
  write.xlsx(dataframes$up, file = paste0(directory,"/",param,"_up.xlsx"))
  write.xlsx(dataframes$datos, file = paste0(directory,"/",param,".xlsx"))
}



````


#KEGG

````{r}

# Function to perform KEGG pathway enrichment analysis
kegg_function <- function(genes){
  
  enrichment_result_up_fil <- enrichKEGG(gene = genes$upregulated_genes_filtered, organism = 'mmu', pvalueCutoff = 0.1)
  enrichment_result_down_fil <- enrichKEGG(gene = genes$downregulated_genes_filtered, organism = 'mmu', pvalueCutoff = 0.1)

  # Process upregulated KEGG pathways
  if(!is.null(enrichment_result_up_fil)){
    kegg_up <- enrichment_result_up_fil@result
    
    # Map ENTREZ IDs to readable gene symbols
    pathway_genes_up_fil <- setReadable(enrichment_result_up_fil, OrgDb = org.Mm.eg.db, keyType = "ENTREZID")
    
    # Export a subset of KEGG enrichment results, omitting missing values
    kegg_up_export <- na.omit(pathway_genes_up_fil@result[, c(1:8, 10)])
    assign(paste("kegg_up_export"), kegg_up_export, envir = .GlobalEnv)
  }
  else{
    assign(paste("kegg_up_export"), 0, envir = .GlobalEnv)
    print("No se encontraron pathways KEGG upregulados")
  }
  
  if(!is.null(enrichment_result_down_fil)){
  kegg_down <- enrichment_result_down_fil@result
  pathway_genes_down_fil <- setReadable(enrichment_result_down_fil, OrgDb = org.Mm.eg.db, keyType = "ENTREZID")
  kegg_down_export <- na.omit(pathway_genes_down_fil@result[, c(1:8, 10)])
  assign(paste("kegg_down_export"), kegg_down_export, envir = .GlobalEnv)
  }
  else{
    assign(paste("kegg_down_export"), 0, envir = .GlobalEnv)
    print("No se encontraron pathways KEGG downregulados")
  }
  
  
  return(list(enrichment_result_up_fil=enrichment_result_up_fil, enrichment_result_down_fil=enrichment_result_down_fil))
}



````

## KEGG analysis


````{r}
process_kegg <- function(result, param, group){
  if (!dir.exists(paste0(group,"/KEGG"))) {
  dir.create(paste0(group,"/KEGG"), recursive = TRUE) 
}

  if (!is.null(result$enrichment_result_up_fil) && nrow(result$enrichment_result_up_fil) > 0) {
    
    
    # Create barplot for upregulated KEGG pathways
    barplot_kegg_up_fil <- barplot(result$enrichment_result_up_fil, showCategory = 10) + ggtitle("Filtered KEGG Pathway Enrichment (Upregulated Genes)")
    
    # Create dotplot for upregulated KEGG pathways
    dotplot_kegg_up_fil <- dotplot(result$enrichment_result_up_fil, showCategory = 10) + ggtitle("Filtered Dotplot of Enriched KEGG Pathways (Upregulated Genes)") 
    
    # Save the plots
    ggsave(paste0(group,"/KEGG/KEGG_Enrichment_BarPlot_up.png"), plot = barplot_kegg_up_fil, height = 10)
    ggsave(paste0(group,"/KEGG/KEGG_Enrichment_DotPlot_up.png"), plot = dotplot_kegg_up_fil, height = 10)
    
    # Convert ENTREZ IDs to readable gene symbols
    edox <- setReadable(result$enrichment_result_up_fil, 'org.Mm.eg.db', 'ENTREZID')
    
    # Compute pairwise term similarity
    resultados_kegg_up <- pairwise_termsim(result$enrichment_result_up_fil)
    
    # Generate tree diagram if termsim contains more than one similarity term
    if (length(resultados_kegg_up@termsim) > 1){
    kegg_tree_up <- treeplot(resultados_kegg_up, nCluster = 2) + ggtitle("Tree Diagram of KEGG Enrichment Upregulated Results")
    
    ggsave(paste0(group,"/KEGG/KEGG_Tree_Diagram_up.png"), plot = kegg_tree_up, width = 16, height = 15, bg = "white")
    }
    
    # Create pathway diagram
    kegg_pathway_up <- cnetplot(edox, colorEdge = TRUE, categorySize = "p.adjust", foldChange = result$enrichment_result_up_fil) +
        ggtitle("Pathway Diagram of KEGG Enrichment Upregulated Results")
    cowplot::plot_grid(kegg_pathway_up, ncol=1)
    ggsave(paste0(group,"/KEGG/KEGG_Pathway_Diagram_up.png"), plot = kegg_pathway_up, width = 20, height = 10, bg="white")
    
    # Create enrichment map
    kegg_emap_up <- emapplot(resultados_kegg_up) + ggtitle("Enrichment Map of KEGG Enrichment Upregulated Results") 
    ggsave(paste0(group,"/KEGG/KEGG_Enrichment_Map_up.png"), plot = kegg_emap_up, width = 15, height = 13, bg = "white")
    genes_in_enrichment <- unique(unlist(strsplit(result$enrichment_result_up_fil@result$geneID, "/")))
    dataset_name <- paste0("final_data")
    dataset_param <- get(dataset_name, envir = .GlobalEnv)
    filtered_foldChange <- dataset_param$logFC[genes_in_enrichment %in% dataset_param$ENTREZID]
    names(filtered_foldChange) <- dataset_param$gene[genes_in_enrichment %in% dataset_param$ENTREZID]
    kegg_heat_up <- heatplot(edox, foldChange = filtered_foldChange)  + ggtitle("Heatmap of Enriched KEGG Terms (Upregulated Genes)") + scale_fill_gradient2(low = "green", mid = "yellow", high = "red", midpoint = 0)  
    ggsave(paste0(group,"/KEGG/KEGG_Enrichment_HeatMap_up.png"), plot = kegg_heat_up, width = 20, height = 7, bg = "white")
    
    # Generate UpSet plot
    upsetplot_up <- upsetplot(result$enrichment_result_up)
    
    ggsave(paste0(group,"/KEGG/KEGG_UpSetPlot_Up.png"), plot = upsetplot_up, width = 10, height = 8, bg = "white")
    } else {
        print("No significant pathways found.")
    }


if (!is.null(result$enrichment_result_down_fil) && nrow(result$enrichment_result_down_fil) > 0) {

    
    
    barplot_kegg_down_fil <- barplot(result$enrichment_result_down_fil, showCategory = 10) + ggtitle("Filtered KEGG Pathway Enrichment (Downregulated Genes)")
    dotplot_kegg_down_fil <- dotplot(result$enrichment_result_down_fil, showCategory = 10) + ggtitle("Filtered Dotplot of Enriched KEGG Pathways (Downregulated Genes)")
    ggsave(paste0(group,"/KEGG/KEGG_Enrichment_BarPlot_down.png"), plot = barplot_kegg_down_fil, height = 10)
    ggsave(paste0(group,"/KEGG/KEGG_Enrichment_DotPlot_down.png"), plot = dotplot_kegg_down_fil, height = 10)
    
    
    edox <- setReadable(result$enrichment_result_down_fil, 'org.Mm.eg.db', 'ENTREZID')

    resultados_kegg_down <- pairwise_termsim(result$enrichment_result_down_fil)
    
    if (length(resultados_kegg_down@termsim) > 1){
    kegg_tree_down <- treeplot(resultados_kegg_down,nCluster=2) + ggtitle("Tree Diagram of KEGG Enrichment Downregulated Results")
    
    ggsave(paste0(group,"/KEGG/KEGG_Tree_Diagram_down.png"), plot = kegg_tree_down, width = 16, height = 15, bg = "white")
    }
    
    kegg_pathway_down <- cnetplot(edox, colorEdge = TRUE, categorySize = "p.adjust", foldChange = result$enrichment_result_down_fil) +
        ggtitle("Pathway Diagram of KEGG Enrichment Downregulated Results")
    
    ggsave(paste0(group,"/KEGG/KEGG_Pathway_Diagram_down.png"), plot = kegg_pathway_down, width = 20, height = 10, bg="white")
    
    kegg_emap_down <- emapplot(resultados_kegg_down) + ggtitle("Enrichment Map of KEGG Enrichment Downregulated Results") 
    
    ggsave(paste0(group,"/KEGG/KEGG_Enrichment_Map_down.png"), plot = kegg_emap_down, width = 15, height = 13, bg = "white")
    
    dataset_name <- paste0(param, "_data")
    dataset_param <- get(dataset_name, envir = .GlobalEnv)
    genes_in_enrichment <- unique(unlist(strsplit(result$enrichment_result_down_fil@result$geneID, "/")))
    filtered_foldChange <- dataset_param$logFC[genes_in_enrichment %in% dataset_param$ENTREZID]
    names(filtered_foldChange) <- dataset_param$gene[genes_in_enrichment %in% dataset_param$ENTREZID]
    
    
    kegg_heat_down <- heatplot(edox, foldChange = filtered_foldChange)  + ggtitle("Heatmap of Enriched KEGG Terms (Downregulated Genes)") + scale_fill_gradient2(low = "green", mid = "yellow", high = "red", midpoint = 0)  
    ggsave(paste0(group,"/KEGG/KEGG_Enrichment_HeatMap_down.png"), plot = kegg_heat_down, width = 20, height = 7, bg = "white")
    
    upsetplot_down <- upsetplot(result$enrichment_result_down_fil)
    ggsave(paste0(group,"/KEGG/KEGG_UpSetPlot_down.png"), plot = upsetplot_down, width = 10, height = 8, bg = "white")
    } else {
        print("No significant pathways found for downregulated genes.")
    }
}







````



# GO

````{r}

go_function <- function(genes){
  # Perform GO enrichment analysis 
  go_result_up <- enrichGO(gene = genes$upregulated_genes_symbol, OrgDb = org.Mm.eg.db, keyType = "SYMBOL", ont = "BP", pvalueCutoff = 0.1, readable = TRUE)
  
  go_result_down <- enrichGO(gene = genes$downregulated_genes_symbol, OrgDb = org.Mm.eg.db, keyType = "SYMBOL", ont = "BP", pvalueCutoff = 0.1, readable = TRUE)
  
  if(!is.null(go_result_up)){
    go_result_u_t <- go_result_up@result
    
    # Order the results by adjusted p-value (from highest to lowest)
    go_result_u_t <- go_result_u_t[order(go_result_u_t$p.adjust, decreasing = TRUE),]
    assign(paste("go_result_u_t"), go_result_u_t, envir = .GlobalEnv)
    
    # Extract and clean up specific columns for export
    go_export_u <- na.omit(go_result_u_t[,c(1:6, 8)])
    assign(paste("go_export_u"), go_export_u, envir = .GlobalEnv)
  }
  else{
    assign(paste("go_export_u"), 0, envir = .GlobalEnv)
    print("No se encontraron funciones upreguladas")
  }
  
  if(!is.null(go_result_down)){
    go_result_d_t <- go_result_down@result
    go_result_d_t <- go_result_d_t[order(go_result_d_t$p.adjust, decreasing = TRUE),]
    assign(paste("go_result_d_t"), go_result_d_t, envir = .GlobalEnv)
    go_export_d <- na.omit(go_result_d_t[,c(1:6, 8)])
    assign(paste("go_export_d"), go_export_d, envir = .GlobalEnv)
  }
  else{
    assign(paste("go_export_d"), 0, envir = .GlobalEnv)
    print("No se encontraron funciones downreguladas")
  }

  
  return(list(go_result_up_fil=go_result_up, go_result_down_fil=go_result_down))
}



````

## GO analysis

````{r}

process_go <- function(result, param, group){
  if (!dir.exists(paste0(group,"/GO"))) {
  dir.create(paste0(group,"/GO"), recursive = TRUE) 
  }
  
  # Extract the GO enrichment results for upregulated and downregulated genes
  go_result_up_fil <- resultado$go_result_up_fil
  go_result_down_fil <- result$go_result_down_fil
  if (!is.null(result$go_result_up_fil) && nrow(result$go_result_up_fil) > 0) {

    # Create barplot, dotplot, and goplot for upregulated GO terms
    barplot_go_up_fil <- barplot(result$go_result_up_fil, showCategory = 10) + ggtitle("Filtered GO Enrichment (Upregulated Genes)")
    dotplot_go_up_fil <- dotplot(result$go_result_up_fil, showCategory = 10) + ggtitle("Filtered Dotplot of Enriched GO Terms (Upregulated Genes)") 
    goplot_go_up_fil <- goplot(result$go_result_up_fil, showCategory = 3) + ggtitle("Filtered Goplot of Enriched GO Terms (Upregulated Genes)")
  
    ggsave(paste0(group,"/GO/Go_Enrichment_BarPlot_up.png"), plot = barplot_go_up_fil, height = 10)
    ggsave(paste0(group,"/GO/Go_Enrichment_DotPlot_up.png"), plot = dotplot_go_up_fil, height = 10)
    ggsave(paste0(group,"/GO/Go_Enrichment_GoPlot_up.png"), plot = goplot_go_up_fil, bg = "white", width = 15, height = 15)
    
    # Convert ENTREZ IDs to readable gene symbols for visualization
    edox <- setReadable(result$go_result_up_fil, 'org.Mm.eg.db', 'SYMBOL')
    
    # Compute pairwise term similarity for GO terms
    resultados_go_up <- pairwise_termsim(result$go_result_up_fil)
    
    # Generate a tree diagram if there are sufficient terms
    if(length(resultados_go_up@termsim) > 1){
    go_tree_up <- treeplot(resultados_go_up) + ggtitle("Tree Diagram of GO Terms Results")
    
    ggsave(paste0(group,"/GO/GO_Tree_Diagram_up.png"), plot = go_tree_up, width = 16, height = 15, bg = "white")
    }
    
    # Generate a tree diagram if there are sufficient terms
    go_pathway_up <- cnetplot(edox, colorEdge = TRUE, categorySize = "p.adjust", foldChange = result$go_result_up_fil, showCategory = 10) +
        ggtitle("Pathway Diagram of KEGG Enrichment Results")
    ggsave(paste0(group,"/GO/GO_Enrichment_Diagram_up.png"), plot = go_pathway_up, width = 20, height = 10, bg = "white")
    
    # Generate a heatmap for GO terms
    dataset_name <- paste0(param, "_data")
    dataset_param <- get(dataset_name, envir = .GlobalEnv)
    genes_in_go <- unique(unlist(strsplit(go_result$go_result_up_fil@result$geneID, "/")))
    filtered_foldChange <- dataset_param$logFC[genes_in_go %in% dataset_param$gene]
    names(filtered_foldChange) <- dataset_param$gene[genes_in_go %in% dataset_param$gene]
    
    go_heat_up <- heatplot(edox, foldChange = filtered_foldChange)  + ggtitle("Heatmap of Enriched GO Terms (Upregulated Genes)") + scale_fill_gradient2(low = "green", mid = "yellow", high = "red", midpoint = 0) 
    
    ggsave(paste0(group,"/GO/Go_Enrichment_HeatMap_up.png"), plot = go_heat_up, width = 30, height = 10, bg = "white")
    
    # Create an UpSet plot
    upsetplot_up <- upsetplot(result$go_result_up_fil)
    ggsave(paste0(group,"/GO/go_UpSetPlot_Up.png"), plot = upsetplot_up, width = 10, height = 8, bg = "white")
  } else {
      print("No significant GO terms found.")
  }
  
  if (!is.null(result$go_result_down_fil) && nrow(result$go_result_down_fil) > 0) {
      
     
      barplot_go_down_fil <- barplot(result$go_result_down_fil, showCategory = 10) + ggtitle("Filtered GO Enrichment (Downregulated Genes)")
      dotplot_go_down_fil <- dotplot(result$go_result_down_fil, showCategory = 10) + ggtitle("Filtered Dotplot of Enriched GO Terms (Downregulated Genes)")
      goplot_go_down_fil <- goplot(result$go_result_down_fil, showCategory = 10) + ggtitle("Filtered Gotplot of Enriched GO Terms (Downregulated Genes)")
      ggsave(paste0(group,"/GO/Go_Enrichment_BarPlot_down.png"), plot = barplot_go_down_fil, height = 10)
      ggsave(paste0(group,"/GO/Go_Enrichment_DotPlot_down.png"), plot = dotplot_go_down_fil, height = 10)
      ggsave(paste0(group,"/GO/Go_Enrichment_GoPlot_down.png"), plot = goplot_go_down_fil, bg = "white", width = 15, height = 15)
      
      edox <- setReadable(result$go_result_down_fil, 'org.Mm.eg.db', 'SYMBOL')
  
  resultados_go_down <- pairwise_termsim(result$go_result_down_fil)
    if(length(resultados_go_down@termsim) > 1){
  go_tree_down <- treeplot(resultados_go_down) + ggtitle("Tree Diagram of GO Terms Results")

  ggsave(paste0(group,"/GO/GO_Tree_Diagram_down.png"), plot = go_tree_down, width = 16, height = 15, bg = "white")
    }
  go_pathway_down <- cnetplot(edox, colorEdge = TRUE, categorySize = "p.adjust", foldChange = result$go_result_down_fil, showCategory = 10) +
      ggtitle("Pathway Diagram of KEGG Enrichment Results")

  ggsave(paste0(group,"/GO/GO_Enrichment_Diagram_down.png"), plot = go_pathway_down, width = 20, height = 10, bg = "white")
  
  dataset_name <- paste0(param, "_data")
  dataset_param <- get(dataset_name, envir = .GlobalEnv)
  genes_in_go <- unique(unlist(strsplit(result$go_result_down_fil@result$geneID, "/")))
  filtered_foldChange <- dataset_param$logFC[genes_in_go %in% dataset_param$gene  ]
  names(filtered_foldChange) <- dataset_param$gene[genes_in_go %in% dataset_param$gene ]
  
  go_heat_down <- heatplot(edox, foldChange = filtered_foldChange)  + ggtitle("Heatmap of Enriched GO Terms (Downregulated Genes)") + scale_fill_gradient2(low = "green", mid = "yellow", high = "red", midpoint = 0)  

  ggsave(paste0(group,"/GO/GO_Enrichment_HeatMap_down.png"), plot = go_heat_down, width = 30, height = 10, bg = "white")
  
  upsetplot_down <- upsetplot(result$go_result_down_fil)

  ggsave(paste0(group,"/GO/go_UpSetPlot_down.png"), plot = upsetplot_down, width = 10, height = 8, bg = "white")
  } else {
      print("No significant GO terms found for downregulated genes.")
  }
}




````


# Reactome

````{r}

reactome_function <- function(genes){
  reactome_result_up_fil <- enrichPathway(gene = genes$upregulated_genes_filtered, organism = "mouse", pvalueCutoff = 0.1, readable = TRUE)

reactome_result_down_fil <- enrichPathway(gene = genes$downregulated_genes_filtered, organism = "mouse", pvalueCutoff = 0.1, readable = TRUE)
if(!is.null(reactome_result_up_fil)){
  reac_result_u_t <- reactome_result_up_fil@result
  reac_result_u_t <- reac_result_u_t[order(reac_result_u_t$p.adjust, decreasing = FALSE),]
  reac_export_u <- reac_result_u_t[,c(1:6, 8)]
  assign(paste("reac_export_u"), reac_export_u, envir = .GlobalEnv)
}
else{
  assign(paste("reac_export_u"), 0, envir = .GlobalEnv)
}

if(!is.null(reactome_result_down_fil)){
  
  reac_result_d_t <- reactome_result_down_fil@result
  reac_result_d_t <- reac_result_d_t[order(reac_result_d_t$p.adjust, decreasing = FALSE),]
  reac_export_d <- reac_result_d_t[,c(1:4, 8)]
  assign(paste("reac_export_d"), reac_export_d, envir = .GlobalEnv)
}
else{
  assign(paste("reac_export_d"), 0, envir = .GlobalEnv)
}
return (list(reactome_result_up_fil=reactome_result_up_fil, reactome_result_down_fil=reactome_result_down_fil))
}



````

## Reactome analysis

````{r}

process_reactome <- function(result,param, group){
  if (!dir.exists(paste0(group,"/Reactome"))) {
  dir.create(paste0(group,"/Reactome"), recursive = TRUE) 
  }
  if (!is.null(result$reactome_result_up_fil) && nrow(result$reactome_result_up_fil) > 0) {

    # Generate barplot and dotplot for upregulated pathways
    barplot_reactome_up_fil <- barplot(result$reactome_result_up_fil, showCategory = 10) + ggtitle("Filtered Reactome Enrichment (Upregulated Genes)")
    dotplot_reactome_up_fil <- dotplot(result$reactome_result_up_fil, showCategory = 10) + ggtitle("Filtered Dotplot of Enriched Reactome Pathways (Upregulated Genes)")
    ggsave(paste0(group,"/Reactome/Reactome_Enrichment_BarPlot_up.png"), plot = barplot_reactome_up_fil, height = 10)
    ggsave(paste0(group,"/Reactome/Reactome_Enrichment_DotPlot_up.png"), plot = dotplot_reactome_up_fil, height = 10)
    
    # Convert gene IDs to readable symbols for visualization
    edox <- setReadable(result$reactome_result_up_fil, 'org.Mm.eg.db', 'ENTREZID')
    
    # Generate term similarity and treeplot
    resultados_reactome_up <- pairwise_termsim(reactome_result$reactome_result_up_fil)
    if (length(resultados_reactome_up@termsim ) > 1){
      reactome_tree_up <- treeplot(resultados_reactome_up, nCluster = 2) + ggtitle("Tree Diagram of Reactome Enrichment Upregulated Results")
    
     ggsave(paste0(group,"/Reactome/Reactome_Tree_Diagram_up.png"), plot = reactome_tree_up, width = 16, height = 15, bg = "white")
    }
reactome_pathway_up <- cnetplot(edox, colorEdge = TRUE, categorySize = "p.adjust", foldChange = result$reactome_result_up_fil, layout = "kk") +
    ggtitle("Pathway Diagram of Reactome Enrichment Upregulated Results")

ggsave(paste0(group,"/Reactome/Reactome_Pathway_Diagram_up.png"), plot = reactome_pathway_up, width = 20, height = 10, bg="white")


    # Generate cnetplot for pathway visualization
    reactome_emap_up <- emapplot(resultados_reactome_up) + ggtitle("Enrichment Map of Reactome Enrichment Upregulated Results") 
    
    ggsave(paste0(group,"/Reactome/Reactome_Enrichment_Map_up.png"), plot = reactome_emap_up, width = 15, height = 13, bg = "white")
    
    
    # Generate heatmap for enriched pathways
    dataset_name <- paste0(param, "_data")
    dataset_param <- get(dataset_name, envir = .GlobalEnv)
    genes_in_reac <- unique(unlist(strsplit(result$reactome_result_up_fil@result$geneID, "/")))
    
    filtered_foldChange <- dataset_param$logFC[genes_in_reac %in% dataset_param$gene  ]
    names(filtered_foldChange) <- dataset_param$gene[genes_in_reac %in% dataset_param$gene  ]
    
    reactome_heat_up <- heatplot(edox, foldChange = filtered_foldChange)  + ggtitle("Heatmap of Enriched Reactome Pathways (Upregulated Genes)") + scale_fill_gradient2(low = "green", mid = "yellow", high = "red", midpoint = 0)   
    ggsave(paste0(group,"/Reactome/Reactome_HeatMap_up.png"), plot = reactome_heat_up, width = 20, height = 10, bg = "white")
} else {
    print("No significant pathways found.")
}

if (!is.null(reactome_result$reactome_result_down_fil) && nrow(result$reactome_result_down_fil) > 0) {
    barplot_reactome_down_fil <- barplot(result$reactome_result_down_fil, showCategory = 10) + ggtitle("Filtered Reactome Pathway Enrichment (Downregulated Genes)")
    dotplot_reactome_down_fil <- dotplot(result$reactome_result_down_fil, showCategory = 10) + ggtitle("Filtered Dotplot of Enriched Reactome Pathways (Downregulated Genes)")
    ggsave(paste0(group,"/Reactome/Reactome_Enrichment_BarPlot_down.png"), plot = barplot_reactome_down_fil)
    ggsave(paste0(group,"/Reactome/Reactome_Enrichment_DotPlot_down.png"), plot = dotplot_reactome_down_fil)
    edox <- setReadable(result$reactome_result_down_fil, 'org.Mm.eg.db', 'ENTREZID')

resultados_reactome_down <- pairwise_termsim(reactome_result$reactome_result_down_fil)
if (length(resultados_reactome_down@termsim ) > 1 ){
reactome_tree_down <- treeplot(resultados_reactome_down, nCluster=2) + ggtitle("Tree Diagram of Reactome Enrichment Downregulated Results")

ggsave(paste0(group,"/Reactome/Reactome_Tree_Diagram_down.png"), plot = reactome_tree_down, width = 16, bg = "white")
}
reactome_pathway_down <- cnetplot(edox, colorEdge = TRUE, categorySize = "p.adjust", foldChange = result$reactome_result_down_fil) +
    ggtitle("Pathway Diagram of Reactome Enrichment Downregulated Results")

ggsave(paste0(group,"/Reactome/Reactome_Pathway_Diagram_down.png"), plot = reactome_pathway_down, width = 20, height = 10, bg="white")

reactome_emap_down <- emapplot(resultados_reactome_down) + ggtitle("Enrichment Map of Reactome Enrichment Downregulated Results") 

ggsave(paste0(group,"/Reactome/Reactome_Enrichment_Map_down.png"), plot = reactome_emap_down, width = 15, height = 13, bg = "white")

dataset_name <- paste0(param, "_data")
  dataset_param <- get(dataset_name, envir = .GlobalEnv)
genes_in_reac <- unique(unlist(strsplit(result$reactome_result_down_fil@result$geneID, "/")))

filtered_foldChange <- dataset_param$logFC[genes_in_reac %in% dataset_param$gene  ]
names(filtered_foldChange) <- dataset_param$gene[genes_in_reac %in% dataset_param$gene  ]

reactome_heat_down <- heatplot(edox, foldChange = filtered_foldChange)  + ggtitle("Heatmap of Enriched Reactome Pathways (Downregulated Genes)") + scale_fill_gradient2(low = "green", mid = "yellow", high = "red", midpoint = 0)  
ggsave(paste0(group,"/Reactome/Reactome_HeatMap_down.png"), plot = reactome_heat_down, width = 20, height = 10, bg = "white")
} else {
    print("No significant pathways found for downregulated genes.")
}
  
  
}




````







````{r}

# Function to get p-values for genes from a given dataframe
get_pvalues <- function(genes, pvalues_df) {
  genes <- unlist(strsplit(genes, "/"))  
  
  # Retrieve the p-values for each gene from the provided dataframe
  pvalues <- sapply(genes, function(gene) {
    if (gene %in% pvalues_df$Gene) {
      return(pvalues_df$pvalue[pvalues_df$Gene == gene])
    } else {
      return(NA)  
    }
  })
  return(paste(pvalues, collapse = "/"))
}

# Function to process and update p-values for enrichment results
get_pvalues_df <- function(result, param){
  
  # Extract and clean dataframes for downregulated and upregulated genes
  pvalues_df_d <- na.omit(result$datos_down %>% select(gene, pvalue) %>% rename(Gene = gene, pvalue = pvalue))
  pvalues_df_u <- na.omit(result$datos_up %>% select(gene, pvalue) %>% rename(Gene = gene, pvalue = pvalue))
  
  
  # Update GO, KEGG and Reactome export with p-values
  if (length(go_export_d)>1){
  go_export_d <- go_export_d %>%
  mutate(pvalues = sapply(geneID, get_pvalues, pvalues_df = pvalues_df_d))
  }
  else{
    assign(paste("go_export_d"), 0, envir = .GlobalEnv)
  }
  if (length(go_export_u)>1){
  go_export_u <- go_export_u %>%
  mutate(pvalues = sapply(geneID, get_pvalues, pvalues_df = pvalues_df_u))
  }
  else{
    assign(paste("go_export_u"), 0, envir = .GlobalEnv)
  }
  
  if (length(kegg_down_export)>1){
  kegg_down_export <- kegg_down_export %>%
  mutate(pvalues = sapply(geneID, get_pvalues, pvalues_df = pvalues_df_d))
  }
  else{
    assign(paste("kegg_down_export"), 0, envir = .GlobalEnv)
  }
  
  if (length(kegg_up_export)>1){
  kegg_up_export <- kegg_up_export %>%
  mutate(pvalues = sapply(geneID, get_pvalues, pvalues_df = pvalues_df_u))
  }
  else{
    assign(paste("kegg_up_export"), 0, envir = .GlobalEnv)
  }
  
  if (length(reac_export_u)>1){
  reac_export_u <- reac_export_u %>%
  mutate(pvalues = sapply(geneID, get_pvalues, pvalues_df = pvalues_df_u))
  }
  else{
    assign(paste("reac_export_u"), 0, envir = .GlobalEnv)
  }
  
  if (length(reac_export_d)>1){
  reac_export_d <- reac_export_d %>%
  mutate(pvalues = sapply(geneID, get_pvalues, pvalues_df = pvalues_df_d))
  }
  else{
    assign(paste("reac_export_d"), 0, envir = .GlobalEnv)
  }
  assign(paste0(param,"_go_d"), go_export_d, envir = .GlobalEnv)
  assign(paste0(param,"_go_u"), go_export_u, envir = .GlobalEnv)
  assign(paste0(param,"_kegg_d"), kegg_down_export, envir = .GlobalEnv)
  assign(paste0(param,"_kegg_u"), kegg_up_export, envir = .GlobalEnv)
  assign(paste0(param,"_reac_d"), reac_export_d, envir = .GlobalEnv)
  assign(paste0(param,"_reac_u"), reac_export_u, envir = .GlobalEnv)
  
  
}


  
  




````






````{r}
# Create dataframes for visualitazion of the results
create_dataframes <- function(result, param){
  dataframes_down <- list("Datos" = result$datos_down,
                   "GO" = get(paste0(param,"_go_d"), envir = .GlobalEnv),
                   "KEGG" = get(paste0(param,"_kegg_d"), envir = .GlobalEnv),
                   "Reactome" = get(paste0(param,"_reac_d"), envir = .GlobalEnv))

  dataframes_up <- list("Datos" = result$datos_up,
                   "GO" = get(paste0(param,"_go_u"), envir = .GlobalEnv),
                   "KEGG" = get(paste0(param,"_kegg_u"), envir = .GlobalEnv),
                   "Reactome" = get(paste0(param,"_reac_u"), envir = .GlobalEnv))
  dataframes_up_down <- list("Datos" = rbind(result$datos_down,result$datos_up),
                             "Go" = rbind(get(paste0(param,"_go_d"), envir = .GlobalEnv), get(paste0(param,"_go_u"), envir = .GlobalEnv)))
  return(list(up=dataframes_up,down=dataframes_down, datos = dataframes_up_down))
}


````


````{r}
# Define the path to the directory containing input files
archivos <- list.files(path = "../Venn", pattern = "\\.xlsx$", full.names = TRUE)
pvaluee <- 0.05 # Set the p-value threshold

for (archivo in archivos){
  
  # Read the input data from the Excel file
  data <- read.xlsx(archivo)
  
  # Extract the sample identifier from the filename
  sample <- gsub(".*([a-zA-Z])\\.xlsx$", "\\1", archivo)
  
  # Read the upregulated and downregulated gene lists for the sample
  genes_up <- sapply(read.xlsx(paste0("../Venn/Resultados/resultados_Up_", sample, ".xlsx")),capitalize_first)
  genes_down <- sapply(read.xlsx(paste0("../Venn/Resultados/resultados_Down_", sample, ".xlsx")), capitalize_first)
  
  # Extract the group identifier from the filename
  grupo <- gsub(".*/.*_([a-zA-Z0-9]{2,})[a-zA-Z]*\\.xlsx$", "\\1", archivo)

  # Assign the appropriate column index for exclusive gene filtering based on the group
  if (grupo == "ML" | grupo == "MS"){
    exclusive_column <- 1
  }
  else if (grupo == "Md4L" | grupo == "Md4S" | grupo == "Md4E"){
    exclusive_column <- 2
    
  }
  else if (grupo == "FL" | grupo == "FS"){
    exclusive_column <- 3
  }

  # Convert protein IDs to ENTREZ IDs using the org.Mm.eg.db database
  uniprot_ids <- unlist(strsplit(as.character(data$protein), split = " "))
  ids_entrez <- bitr(uniprot_ids, fromType = "UNIPROT", toType = "ENTREZID", OrgDb = org.Mm.eg.db)
  
  # Map genes to their ENTREZ IDs
  up_entrez <- sapply(as.character(data$protein[data$gene%in%na.omit(genes_up[, exclusive_column])]), function(x) {
      ids <- unlist(strsplit(x, split = " "))  
      matched_ids <- ids_entrez$ENTREZID[ids_entrez$UNIPROT %in% ids]  
      if (length(matched_ids) > 0) {
          paste(unique(matched_ids), collapse = ";")  
      } else {
          NA  
      }
  })
  up_entrez <- as.data.frame(up_entrez)
  if (dim(up_entrez)[1] > 0){
    colnames(up_entrez) <- "ENTREZID"
  }
  down_entrez <- sapply(as.character(data$protein[data$gene %in% 
                  na.omit(genes_down[, exclusive_column])]), function(x) {
      ids <- unlist(strsplit(x, split = " "))  
      matched_ids <- ids_entrez$ENTREZID[ids_entrez$UNIPROT %in% ids]  
      if (length(matched_ids) > 0) {
          paste(unique(matched_ids), collapse = ";")  
      } else {
          NA  
      }
  })
  
  down_entrez <- as.data.frame(down_entrez)

  if (dim(down_entrez)[1] > 0){
    colnames(down_entrez) <- "ENTREZID"
  }
  # Add ENTREZ IDs to the original dataset
  data$ENTREZID <- sapply(as.character(data$protein), function(x) {
      ids <- unlist(strsplit(x, split = " "))
      matched_ids <- ids_entrez$ENTREZID[ids_entrez$UNIPROT %in% ids]
      if (length(matched_ids) > 0) {
          paste(unique(matched_ids), collapse = ";")
      } else {
          NA
      }
  })
  
  # Capitalize gene names
  data$gene<- sapply(data$gene, capitalize_first)
  
  # Filter and process the data
  final_data <- create_filtered_data(data)
  resultado <- generate_data(final_data, exclusive_column, 1)
  
  # Generate upregulated and downregulated gene lists
  genes <- generate_genes(resultado, genes_up,genes_down, exclusive_column)
  
  directory <- paste0("combined/",grupo, sample)
  name <- paste0(grupo, sample)
  
  # Perform KEGG enrichment analysis and generate visualizations
  kegg_result <- kegg_function(genes)
  process_kegg(kegg_result, "final", directory)
  
  # Perform GO enrichment analysis and generate visualizations
  go_result <- go_function(genes)
  process_go(go_result, "final", directory)
  
  # Perform Reactome enrichment analysis and generate visualizations
  reactome_result <- reactome_function(genes)
  process_reactome(reactome_result, "final", directory)
  
  # Update enrichment results with p-values
  get_pvalues_df(resultado, "final")
  
  # Create structured dataframes for upregulated, downregulated, and combined results
  dataframes_final <- create_dataframes(resultado,"final")
  
  # Save the final results to files
  write_dataframe(dataframes_final, directory, name)
}

#Repeat the previous proccess but with proteins obtained from common proteins method

for (archivo in archivos){
  
  data <- read.xlsx(archivo)
  sample <- gsub(".*([a-zA-Z])\\.xlsx$", "\\1", archivo)
  print(sample)
  genes_up <- sapply(read.xlsx(paste0("../Venn/Resultados/resultados_Up_", sample, "_nc.xlsx")),capitalize_first)
  genes_down <- sapply(read.xlsx(paste0("../Venn/Resultados/resultados_Down_", sample, "_nc.xlsx")), capitalize_first)
  grupo <- gsub(".*/.*_([a-zA-Z0-9]{2,})[a-zA-Z]*\\.xlsx$", "\\1", archivo)
  print(grupo)
  if (grupo == "ML" | grupo == "MS"){
    exclusive_column <- 1
  }
  else if (grupo == "Md4L" | grupo == "Md4S" | grupo == "Md4E"){
    exclusive_column <- 2
  }
  else if (grupo == "FL" | grupo == "FS"){
    exclusive_column <- 3
  }
  print(exclusive_column)
  uniprot_ids <- unlist(strsplit(as.character(data$protein), split = " "))
  ids_entrez <- bitr(uniprot_ids, fromType = "UNIPROT", toType = "ENTREZID", OrgDb = org.Mm.eg.db)
  if (!is.null(dim(genes_up))){
  up_entrez <- sapply(as.character(data$protein[data$gene%in% 
                  na.omit(genes_up[, exclusive_column])]), function(x) {
      ids <- unlist(strsplit(x, split = " "))  
      matched_ids <- ids_entrez$ENTREZID[ids_entrez$UNIPROT %in% ids]  
      if (length(matched_ids) > 0) {
          paste(unique(matched_ids), collapse = ";")  
      } else {
          NA  
      }
  })
  up_entrez <- as.data.frame(up_entrez)
  if (dim(up_entrez)[1] > 0){
    colnames(up_entrez) <- "ENTREZID"
  }
  }
  if (!is.null(dim(genes_down))){
  down_entrez <- sapply(as.character(data$protein[data$gene %in% 
                  na.omit(genes_down[, exclusive_column])]), function(x) {
      ids <- unlist(strsplit(x, split = " "))  
      matched_ids <- ids_entrez$ENTREZID[ids_entrez$UNIPROT %in% ids]  
      if (length(matched_ids) > 0) {
          paste(unique(matched_ids), collapse = ";")  
      } else {
          NA  
      }
  })
  
  down_entrez <- as.data.frame(down_entrez)

if (dim(down_entrez)[1] > 0){
  colnames(down_entrez) <- "ENTREZID"
}
  }
  data$ENTREZID <- sapply(as.character(data$protein), function(x) {
      ids <- unlist(strsplit(x, split = " "))
      matched_ids <- ids_entrez$ENTREZID[ids_entrez$UNIPROT %in% ids]
      if (length(matched_ids) > 0) {
          paste(unique(matched_ids), collapse = ";")
      } else {
          NA
      }
  })
  if (!is.null(dim(genes_up)) & !is.null(dim(genes_down))){
  data$gene<- sapply(data$gene, capitalize_first)
  final_data <- create_filtered_data(data)
  resultado <- generate_data(final_data, exclusive_column, 1)
  genes <- generate_genes(resultado, genes_up,genes_down, exclusive_column)
  
  directory <- paste0("commun/",grupo, sample)
  name <- paste0(grupo, sample)
  
  kegg_result <- kegg_function(genes)
  process_kegg(kegg_result, "final", directory)
  go_result <- go_function(genes)
  process_go(go_result, "final", directory)
  reactome_result <- reactome_function(genes)
  process_reactome(reactome_result, "final", directory)
  
  get_pvalues_df(resultado, "final")
  dataframes_final <- create_dataframes(resultado,"final")
  write_dataframe(dataframes_final, directory, name)
  }
}






````
