---
title: "PCA"
author: "Andrés Molina Ribagorda"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

````{r}
library(tidyverse)
library(dplyr)
library(writexl)
library(factoextra)  # Para visualización de PCA
library(readxl)
library(ggplot2)
library(VIM)
library(affy)
library(limma)
library(pcaMethods)
````

````{r}

# Read the input data from an Excel file
data <- read_excel("../data_dea.xlsx")

# Extract column names from the dataset
column_names <- colnames(data)

# Identify statistical groups based on patterns in column names
statistical_groups <- unique(grep("ebayes|deqms|msempire|msqrob", column_names, value = TRUE))

# Extract comparative groups using regex patterns
comparative_groups <- unique(sub(".*:(.*)\\#.*", "\\1", grep(":.*\\#", column_names, value = TRUE)))


# Export datasets for each comparison
export_comparative_groups <- function(data, comparative_groups) {
  
  for (group in comparative_groups) {
    # Filter columns related to the current group
    filtered_columns <- colnames(data)[grepl(group, colnames(data))]
  
    # Extract unique prefixes from the group name
    prefixes <- unique(unlist(strsplit(group, "\\.|vs\\.|_")))
    prefixes <- prefixes[prefixes != ""]
    prefixes <- prefixes[!prefixes %in% c("L", "S", "Exo")] 
    prefixes <- substr(prefixes, 1, 2)
    relevant_columns <- colnames(data)[sapply(colnames(data), function(column) {
      any(startsWith(column, prefixes))
    })]
    
    
    final_columns <- c("protein_id", "gene_symbols_or_id", filtered_columns,relevant_columns)
    final_columns <- unique(final_columns) 
    

    filtered_data <- data[, final_columns, drop = FALSE]
  

    output_file <- paste0(group, ".xlsx")
    

    write_xlsx(filtered_data, output_file)
    
    cat("Exported file:", output_file, "\n")
  }
}

export_comparative_groups(data, comparative_groups)

all_data <- data[,1:29]

````

````{r}
# Analysis of full data
data <- all_data[2:29] #Select data of interest

png("boxplot_no_norm.png", width = 800, height = 600)

# Save the initial boxplot to a PNG file
boxplot_no_norm <- boxplot(data,
        main = "Mass data distribution",
        xlab = "Samples",
        ylab = "Mass",
        las = 2,
        col = "lightgreen")


dev.off()

````

````{r}
# Normalitation of full data

# Convert the data to a matrix for normalization
matriz_abundancia <- as.matrix((data))  
rownames(matriz_abundancia) <- t(all_data$protein_id)

# Perform quantile normalization
datos_normalizados <- normalizeBetweenArrays(t(matriz_abundancia), method = "quantile")

datos_normalizados_df <- as.data.frame(t(datos_normalizados))
datos_normalizados_df$Uniprot <- all_data$protein_id




png("boxplot_norm.png", width = 800, height = 600)


boxplot_no_norm <- boxplot(datos_normalizados_df[1:28],
        main = "Mass data distribution",
        xlab = "Samples",
        ylab = "Mass",
        las = 2,
        col = "lightgreen")


dev.off()
````

````{r}

#PCA of full data

# Create a copy of normalized data for PCA
data_norm <- datos_normalizados_df

# Transpose the data matrix for PCA (samples as rows, variables as columns)
data_t <- t(data_norm[,1:28])  


colnames(data_t) <- all_data[[1]]
data_df <- as.data.frame(data_t)

# Convert the data frame into a matrix for PCA analysis
data_matrix <- as.matrix(data_df)

# Perform probabilistic PCA (ppca) with 2 principal components
ppca_result <- pca(data_matrix, method = "ppca", nPcs = 2, seed = 123)

# Extract PCA scores and convert them to a data frame
ppca_scores <- as.data.frame(scores(ppca_result))
ppca_scores$Muestra <- rownames(ppca_scores)


# Load labels for samples from an Excel file
etiquetas_path <- "../Etiquetas.xlsx"  
etiquetas <- read_excel(etiquetas_path)

# Merge PCA scores with sample labels
ppca_data_comp <- left_join(ppca_scores, etiquetas, by = "Muestra")

# Calculate explained variance for each principal component
explained_variance <- (ppca_result@R2) * 100
x_label <- paste0("PC1 (", round(explained_variance[1], 2), "% variance explained)")
y_label <- paste0("PC2 (", round(explained_variance[2], 2), "% variance explained)")

# Create a PCA scatter plot with ggplot2
ppca_plot <- ggplot(ppca_data_comp, aes(x = PC1, y = PC2, color = Sample, shape = Genotype, label = CellType)) +
  geom_point(size = 3, alpha = 0.7) +  
  geom_text(vjust = 1.5, hjust = 1, check_overlap = FALSE, size = 3) +  
  theme_minimal() +  # Tema limpio
  ggtitle("PCA") +
  xlab(x_label) +
  ylab(y_label) +
  theme(legend.position = "right")


ggsave("PCA_all_norm.png", plot = ppca_plot, width = 7, height = 5, bg="white")

````


````{r}

#Normalitation of data without MS2
matriz_abundancia <- as.matrix((all_data[2:28]))  
rownames(matriz_abundancia) <- t(all_data$protein_id)

datos_normalizados <- normalizeBetweenArrays(t(matriz_abundancia), method = "quantile")

datos_normalizados_df <- as.data.frame(t(datos_normalizados))
datos_normalizados_df$Uniprot <- all_data$protein_id

png("boxplot_no_norm_no_S.png", width = 800, height = 600)


boxplot_no_norm <- boxplot(datos_normalizados_df[1:27],
        main = "Mass data distribution",
        xlab = "Samples",
        ylab = "Mass",
        las = 2,
        col = "lightgreen")


dev.off()


````

````{r}

#PCA without MS2
data_norm <- datos_normalizados_df

data_t <- t(data_norm[,1:27])  
colnames(data_t) <- all_data[[1]]
data_df <- as.data.frame(data_t)

data_matrix <- as.matrix(data_df)

ppca_result <- pca(data_matrix, method = "ppca", nPcs = 2, seed = 123)

ppca_scores <- as.data.frame(scores(ppca_result))
ppca_scores$Muestra <- rownames(ppca_scores)


library(readxl)
etiquetas_path <- "Etiquetas.xlsx"  
etiquetas <- read_excel(etiquetas_path)


library(dplyr)
ppca_data_comp <- left_join(ppca_scores, etiquetas, by = "Muestra")


explained_variance <- (ppca_result@R2) * 100
x_label <- paste0("PC1 (", round(explained_variance[1], 2), "% variance explained)")
y_label <- paste0("PC2 (", round(explained_variance[2], 2), "% variance explained)")


library(ggplot2)
ppca_plot <- ggplot(ppca_data_comp, aes(x = PC1, y = PC2, color = Sample, shape = Genotype, label = CellType)) +
  geom_point(size = 3, alpha = 0.7) +  
  geom_text(vjust = 1.5, hjust = 1, check_overlap = FALSE, size = 3) +  
  theme_minimal() +  # Tema limpio
  ggtitle("PCA without outlier") +
  xlab(x_label) +
  ylab(y_label) +
  theme(legend.position = "right")

ggsave("PCA_no_S_norm.png", plot = ppca_plot, width = 7, height = 5, bg="white")
````

  
  